FROM ubuntu:24.04 AS builder

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN gcc -Wall -pthread -o /app/server server.c map.c -lpthread && \
    gcc -Wall -pthread -o /app/client client.c map.c -lpthread

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y gawk && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/server /app/server
COPY --from=builder /app/client /app/client

RUN mkdir -p /app/data

EXPOSE 8080