version: '3.8'

networks:
  game-net:
    driver: bridge

services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: traccialso-server:latest
    container_name: server_container
    ports:
      - "8080:8080"
    volumes:
      - ./users.txt:/app/users.txt
      - ./score.txt:/app/score.txt
      - ./filelog.txt:/app/filelog.txt
    networks:
      - game-net
    restart: "no"